[project]
name = "pro-2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "chainlit>=2.6.7",
    "dotenv>=0.9.9",
    "openai-agents>=0.2.4",
]
